#!/bin/bash

set -euxo pipefail

cat << EOF >> packages.x86_64
cloud-init
growpart
EOF

cat << EOF >> airootfs/root/customize_airootfs.sh

systemctl enable \\
    cloud-init-local.service \\
    cloud-init.service \\
    cloud-config.service \\
    cloud-final.service
EOF
