#!/usr/bin/env bash

set -euxo pipefail

cat << EOF
#cloud-config

# Use systemd instead of netctl. This is also a workaround for the
# problem that network-config does not work well in Arch Linux.
#
# @ref: https://bugs.launchpad.net/cloud-init/+bug/1714495
bootcmd:
- |
    cat << EOF > /etc/systemd/network/ethernet.network
    [Match]
    Name=eth0

    [Network]
    DHCP=yes
    EOF

ssh_authorized_keys:
- "$(cat "${OUT_SSH_KEY_PUB}")"
EOF
