#!/usr/bin/expect

set timeout $env(CASE_TIMEOUT_SECS)

spawn qemu-serial

send "\n"

expect {
  eof {
    puts "Failed to get login prompt (eof)"
    exit 1
  }
  timeout {
    puts "Failed to get login prompt (timeout)"
    exit 1
  }
  "$env(QEMU_NAME) login:"
}

puts "Passed"
