#!/usr/bin/expect

set timeout $env(TEST_TIMEOUT_SECS)

set greeting "Hello world!"

spawn qemu-ssh echo $greeting

expect {
  eof {
    puts "Failed to get command prompt (eof)"
    exit 1
  }
  timeout {
    puts "Failed to get command prompt (timeout)"
    exit 1
  }
  "$greeting"
}

puts "Passed"
