#!/usr/bin/expect

set timeout $env(CASE_TIMEOUT_SECS)

spawn qemu-ssh ls -1 /sys/class/net

set ethernet_interface "eth0"

expect {
  eof {
    puts "Failed to get '$ethernet_interface' (eof)"
    exit 1
  }
  timeout {
    puts "Failed to get '$ethernet_interface' (timeout)"
    exit 1
  }
  "$ethernet_interface"
}

puts "Passed"
