#!/usr/bin/expect

set timeout 10

spawn qemu-ssh ls -1 /sys/class/net

set ethernet_interface "eth0"

expect {
  eof {
    puts "Failed to get '$ethernet_interface'"
    exit 1
  }
  timeout {
    puts "Failed to get '$ethernet_interface'"
    exit 1
  }
  "$ethernet_interface"
}

puts "Passed"
