#!/usr/bin/expect

set timeout $env(TEST_TIMEOUT_SECS)

spawn qemu-ssh sudo passwd -S root

expect {
  eof {
    puts "Failed to get root password status"
    exit 1
  }
  timeout {
    puts "Failed to get root password status"
    exit 1
  }
  "root NP " {
    puts "Root is not locked"
    exit 1
  }
  "root P " {
    puts "Root is not locked"
    exit 1
  }
  "root L "
}

puts "Passed"
