#!/usr/bin/expect

set timeout $env(CASE_TIMEOUT_SECS)

spawn qemu-ssh sudo passwd -S root

expect {
  eof {
    puts "Failed to get root password status (eof)"
    exit 1
  }
  timeout {
    puts "Failed to get root password status (timeout)"
    exit 1
  }
  "root NP " {
    puts "Root is not locked (has no password)"
    exit 1
  }
  "root P " {
    puts "Root is not locked (has password)"
    exit 1
  }
  "root L "
}

puts "Passed"
